# Version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

install:
  - set JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - cd C:\projects\logstash
  - ps: Start-FileDownload 'https://s3.amazonaws.com/jruby.org/downloads/1.7.26/jruby-bin-1.7.26.zip'
  - ps: 7z x C:\projects\logstash\jruby-bin-1.7.26.zip -oC:\projects\logstash -y
  - set PATH=C:\projects\logstash\jruby-1.7.26\bin;%PATH%

build_script:
  - ruby -v
  - appveyor AddCompilationMessage "Creating the Logstash zip artifact"
  - cd C:\projects\logstash
  - rake artifact:zip
  - appveyor AddCompilationMessage "Unzipping the Logstash zip artifact"
  - ps: 7z x C:\projects\logstash\build\*.zip -oC:\projects\logstash\build -y
  - ps: Rename-Item -Path C:\projects\logstash\build\logstash
  - appveyor AddCompilationMessage "Installing core plugins for test"
  - rake test:install-core

test_script:
  #- appveyor AddCompilationMessage "Testing core plugins test:core"
  #- rake test:core
  - appveyor AddCompilationMessage "Integration Tests"
  - ps: C:\projects\logstash\ci\windows\appveyor_integration_run.ps1
